### ISSUE TITLE
zincrby has changed param order

### ISSUE THREAD

**Issue by fabrei** [CIRCL/potiron#30]
in rediy-py (> 2.X) the parameter order of the `zincrby`-method [has changed](https://github.com/andymccurdy/redis-py#zincrby). this affects the modules `potiron-json-layer2.py`, `potiron_redis.py `and `potiron-json-tshark.py`.

**Comment by chrisr3d** [comment]
It is indeed a change I considered in the recent kind of rework I did in the repo
Please have a look at the updated documentation
Btw, thank you for reporting this issue, and of course do not hesitate to poke us again if anything goes wrong
